SHELL := /bin/bash
.RECIPEPREFIX := >
BUILD_DIR ?= /tmp/proberca-p12-build
CLANG ?= clang
CC ?= cc
BPF_CFLAGS := -g -O2 -target bpf -D__TARGET_ARCH_x86 -Wall -Werror -I$(BUILD_DIR) -Ibpf/common -I/usr/include/$(shell uname -m)-linux-gnu
USER_CFLAGS := -g -O2 -Wall -Wextra -Werror -Ibpf/common
PROBES := process sched futex block tcp dns
BPF_OBJECTS := $(addprefix $(BUILD_DIR)/,$(addsuffix .bpf.o,$(PROBES)))
COMMON_HEADERS := bpf/common/common.h bpf/common/event.h bpf/common/maps.h bpf/common/map_contract.h bpf/common/filters.h

.PHONY: all clean
all: $(BUILD_DIR)/vmlinux.h $(BPF_OBJECTS) $(BUILD_DIR)/proberca-ebpf-loader

$(BUILD_DIR):
>install -d -m 0755 "$@"

$(BUILD_DIR)/vmlinux.h: | $(BUILD_DIR)
>@test -r /sys/kernel/btf/vmlinux
>bpftool btf dump file /sys/kernel/btf/vmlinux format c > "$@.tmp"
>mv "$@.tmp" "$@"

define PROBE_template
$(BUILD_DIR)/$(1).bpf.o: bpf/$(1)/$(1).bpf.c $(COMMON_HEADERS) $(BUILD_DIR)/vmlinux.h | $(BUILD_DIR)
>$(CLANG) $(BPF_CFLAGS) -c "$$<" -o "$$@.tmp"
>mv "$$@.tmp" "$$@"
endef
$(foreach probe,$(PROBES),$(eval $(call PROBE_template,$(probe))))

$(BUILD_DIR)/proberca-ebpf-loader: bpf/user/proberca_ebpf_loader.c bpf/common/event.h bpf/common/map_contract.h | $(BUILD_DIR)
>$(CC) $(USER_CFLAGS) "$<" -o "$@.tmp" -lbpf -lelf -lz
>chmod 0755 "$@.tmp"
>mv "$@.tmp" "$@"

clean:
>rm -rf -- "$(BUILD_DIR)"
