from __future__ import annotations

import ast
from pathlib import Path


COVERAGE = {
    1: "tests/test_p10_manifest_reader.py::test_manifest_loads_and_validates_all_declared_hashes",
    2: "tests/test_p10_manifest_reader.py::test_manifest_rejects_path_traversal_and_absolute_paths",
    3: "tests/test_p10_manifest_reader.py::test_manifest_rejects_missing_file",
    4: "tests/test_p10_manifest_reader.py::test_manifest_rejects_hash_mismatch",
    5: "tests/test_p10_manifest_reader.py::test_reader_rejects_record_schema_not_declared_by_manifest",
    6: "tests/test_p10_manifest_reader.py::test_reader_rejects_record_cluster_mismatch",
    7: "tests/test_p10_all_disk_e2e.py::test_runner_rejects_manifest_config_window_mismatch",
    8: "tests/test_p10_manifest_reader.py::test_manifest_rejects_embedded_ground_truth",
    9: "tests/test_p10_manifest_reader.py::test_reader_rejects_non_evidence_record_in_evidence_file",
    10: "tests/test_p10_manifest_reader.py::test_reader_never_opens_labels_file",
    11: "tests/test_p10_manifest_reader.py::test_reader_streams_parquet_and_jsonl_into_window_input",
    12: "tests/test_p10_manifest_reader.py::test_reader_streams_parquet_and_jsonl_into_window_input",
    13: "tests/test_p10_manifest_reader.py::test_reader_strict_mode_rejects_file_internal_disorder",
    14: "tests/test_p10_manifest_reader.py::test_reader_explicit_reorder_is_deterministic_and_records_issue",
    15: "tests/test_p10_manifest_reader.py::test_duplicate_identical_record_is_idempotent",
    16: "tests/test_p10_manifest_reader.py::test_duplicate_same_identity_different_value_fails",
    17: "tests/test_p10_manifest_reader.py::test_reader_does_not_emit_empty_windows_or_fill_missing_values",
    18: "tests/test_p10_manifest_reader.py::test_reader_explicit_reorder_is_deterministic_and_records_issue",
    19: "tests/test_p10_manifest_reader.py::test_reader_streams_parquet_and_jsonl_into_window_input",
    20: "tests/test_p10_manifest_reader.py::test_reader_streams_parquet_and_jsonl_into_window_input",
    21: "tests/test_p10_engine.py::test_engine_uses_one_canonical_stage_order_and_soft_does_not_diagnose",
    22: "tests/test_p10_engine.py::test_engine_uses_one_canonical_stage_order_and_soft_does_not_diagnose",
    23: "tests/test_p10_engine.py::test_engine_uses_one_canonical_stage_order_and_soft_does_not_diagnose",
    24: "tests/test_p10_engine.py::test_engine_uses_one_canonical_stage_order_and_soft_does_not_diagnose",
    25: "tests/test_p10_engine.py::test_engine_uses_one_canonical_stage_order_and_soft_does_not_diagnose",
    26: "tests/test_p10_engine.py::test_engine_uses_one_canonical_stage_order_and_soft_does_not_diagnose",
    27: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    28: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    29: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    30: "tests/test_p10_engine.py::test_analysis_delay_keeps_hard_anchor_and_waits_for_cutoff",
    31: "tests/test_p10_engine.py::test_analysis_delay_keeps_hard_anchor_and_waits_for_cutoff",
    32: "tests/test_p10_engine.py::test_analysis_delay_keeps_hard_anchor_and_waits_for_cutoff",
    33: "tests/test_p10_engine.py::test_checkpoint_restores_frozen_models_and_continues_diagnosis",
    34: "tests/test_p10_engine.py::test_same_hard_state_does_not_start_duplicate_incident",
    35: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    36: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    37: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    38: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    39: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    40: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    41: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    42: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    43: "tests/test_p6_joint_system.py::test_candidate_and_signal_mismatches_fail_fast",
    44: "tests/test_p10_engine.py::test_p5_not_ready_is_failure_without_service_only_or_fake_report",
    45: "tests/test_p6_joint_system.py::test_missing_formal_rows_fail_instead_of_partial_success",
    46: "tests/test_p7_evidence_weighting.py::test_conflicting_duplicate_evidence_id_fails",
    47: "tests/test_p8_fista_solver.py::test_max_iterations_raises_in_strict_mode",
    48: "tests/test_p9_candidates_counterfactual.py::test_input_mismatch_fails_fast",
    49: "tests/test_p10_engine.py::test_p5_not_ready_is_failure_without_service_only_or_fake_report",
    50: "tests/test_p10_runner_cli.py::test_evaluator_keeps_failures_ambiguous_and_denominators_separate",
    51: "tests/test_p10_all_disk_e2e.py::test_cli_exit_code_3_for_real_incident_failure",
    52: "tests/test_p10_all_disk_e2e.py::test_cli_exit_code_3_for_real_incident_failure",
    53: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    54: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    55: "tests/test_p10_engine.py::test_analysis_delay_keeps_hard_anchor_and_waits_for_cutoff",
    56: "tests/test_p7_weighted_problem.py::test_unknown_target_and_raw_burst_record_are_rejected",
    57: "tests/test_p7_weighted_problem.py::test_evidence_contract_adversarial_mutations",
    58: "tests/test_p10_manifest_reader.py::test_reader_never_opens_labels_file",
    59: "tests/test_p7_evidence_weighting.py::test_circular_and_non_independent_evidence_are_excluded_with_provenance",
    60: "tests/test_p10_checkpoint_atomicity.py::test_checkpoint_uses_generation_and_atomic_current_pointer",
    61: "tests/test_p10_engine.py::test_healthy_checkpoint_restores_training_and_runtime_histories",
    62: "tests/test_p10_engine.py::test_checkpoint_restores_frozen_models_and_continues_diagnosis",
    63: "tests/test_p10_engine.py::test_checkpoint_restores_frozen_models_and_continues_diagnosis",
    64: "tests/test_p10_engine.py::test_checkpoint_restores_frozen_models_and_continues_diagnosis",
    65: "tests/test_p10_engine.py::test_checkpoint_restores_frozen_models_and_continues_diagnosis",
    66: "tests/test_p10_resume_continuity.py::test_resume_to_original_output_is_idempotent_and_complete",
    67: "tests/test_p10_resume_continuity.py::test_resume_to_new_output_rebuilds_complete_history",
    68: "tests/test_p10_resume_continuity.py::test_resume_to_new_output_rebuilds_complete_history",
    69: "tests/test_p10_checkpoint_atomicity.py::test_corrupt_current_or_selected_generation_fails_fast",
    70: "tests/test_p10_engine_contracts.py::test_orchestration_config_rejects_degraded_or_invalid_modes",
    71: "tests/test_p10_checkpoint_atomicity.py::test_corrupt_current_or_selected_generation_fails_fast",
    72: "tests/test_p10_runner_cli.py::test_runner_and_manual_window_execution_are_identical",
    73: "tests/test_p10_runner_cli.py::test_runner_and_manual_window_execution_are_identical",
    74: "tests/test_p10_runner_cli.py::test_runner_and_manual_window_execution_are_identical",
    75: "tests/test_p10_runner_cli.py::test_runner_and_manual_window_execution_are_identical",
    76: "tests/test_p10_resume_continuity.py::test_resume_to_new_output_rebuilds_complete_history",
    77: "tests/test_p10_manifest_reader.py::test_reader_explicit_reorder_is_deterministic_and_records_issue",
    78: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    79: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    80: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    81: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    82: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    83: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    84: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    85: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    86: "tests/test_p6_joint_system.py::test_edge_shock_zero_parent_case_has_required_joint_structure",
    87: "tests/test_p10_e2e_cases.py::test_propagated_downstream_symptom_is_not_promoted_over_current_root",
    88: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    89: "tests/test_p10_all_disk_e2e.py::test_all_cases_use_manifest_parquet_jsonl_runner_and_evaluator",
    90: "tests/test_p10_manifest_reader.py::test_reader_never_opens_labels_file",
    91: "tests/test_p10_runner_cli.py::test_runner_does_not_import_labels_or_late_stage_builders",
    92: "tests/test_p10_all_disk_e2e.py::test_changing_independent_label_does_not_change_report_fingerprint",
    93: "tests/test_p10_all_disk_e2e.py::test_all_cases_execute_real_cli_normal_and_evaluation_modes",
    94: "tests/test_p10_runner_cli.py::test_evaluator_keeps_failures_ambiguous_and_denominators_separate",
    95: "tests/test_p10_runner_cli.py::test_evaluator_keeps_failures_ambiguous_and_denominators_separate",
    96: "tests/test_p10_runner_cli.py::test_evaluator_keeps_failures_ambiguous_and_denominators_separate",
    97: "tests/test_p10_runner_cli.py::test_evaluator_keeps_failures_ambiguous_and_denominators_separate",
    98: "tests/test_p10_runner_cli.py::test_evaluator_keeps_failures_ambiguous_and_denominators_separate",
    99: "tests/test_p10_runner_cli.py::test_runner_and_manual_window_execution_are_identical",
    100: "tests/test_p10_engine_contracts.py::test_p10_config_defaults_are_strict_and_backward_compatible",
    101: "tests/test_p10_runner_cli.py::test_repeated_replay_has_same_fingerprint_and_cli_runs",
    102: "tests/test_p10_runner_cli.py::test_repeated_replay_has_same_fingerprint_and_cli_runs",
    103: "tests/test_p10_runner_cli.py::test_repeated_replay_has_same_fingerprint_and_cli_runs",
    104: "tests/test_p10_manifest_reader.py::test_reader_explicit_reorder_is_deterministic_and_records_issue",
    105: "tests/test_p10_all_disk_e2e.py::test_all_cases_execute_real_cli_normal_and_evaluation_modes",
    106: "tests/test_p10_all_disk_e2e.py::test_cli_exit_code_2_for_input_failure",
    107: "tests/test_p10_all_disk_e2e.py::test_cli_exit_code_3_for_real_incident_failure",
    108: "tests/test_p10_all_disk_e2e.py::test_cli_exit_code_4_for_checkpoint_failure",
    109: "tests/test_p10_all_disk_e2e.py::test_cli_exit_code_5_for_evaluation_failure",
    110: "tests/test_p10_runner_cli.py::test_runner_does_not_import_labels_or_late_stage_builders",
    111: "tests/test_p10_all_disk_e2e.py::test_p10_production_has_no_hardcoding_labels_or_stage_bypass",
    112: "tests/test_p10_all_disk_e2e.py::test_p10_production_has_no_hardcoding_labels_or_stage_bypass",
    113: "tests/test_p10_all_disk_e2e.py::test_p10_production_has_no_hardcoding_labels_or_stage_bypass",
    114: "tests/test_p10_runner_cli.py::test_runner_does_not_import_labels_or_late_stage_builders",
    115: "tests/test_p10_all_disk_e2e.py::test_p10_production_has_no_hardcoding_labels_or_stage_bypass",
    116: "tests/test_p10_engine.py::test_hard_anchor_runs_real_p6_to_p9_and_returns_unified_report",
    117: "tests/test_p6_serialization_adversarial.py::test_p6_production_path_has_no_forbidden_dependency_or_fallback",
    118: "tests/test_p7_weighted_problem.py::test_unknown_target_and_raw_burst_record_are_rejected",
    119: "tests/test_p10_manifest_reader.py::test_reader_never_opens_labels_file",
    120: "tests/test_p10_runner_cli.py::test_runner_and_manual_window_execution_are_identical",
}


def test_original_p10_requirements_have_real_test_function_coverage():
    assert set(COVERAGE) == set(range(1, 121))
    parsed = {}
    for requirement, target in COVERAGE.items():
        file_name, function_name = target.split("::", 1)
        path = Path(file_name)
        assert path.is_file(), f"requirement {requirement}: missing {file_name}"
        functions = parsed.setdefault(
            path, {node.name for node in ast.parse(path.read_text(encoding="utf-8")).body
                   if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))})
        assert function_name in functions, (
            f"requirement {requirement}: missing test function {target}")
        assert function_name.startswith("test_")
